//
// Generated File!
//
// This file is Auto Generated by AssetsGenerator Plugin and should not be edited
// since it will be replaced by next plugin execution.
//

import Foundation
import UIKit

#if SWIFT_PACKAGE
private let resourceBundle = Foundation.Bundle.module
#else
private class ResourceBundleClass {}
private let resourceBundle = Foundation.Bundle(for: ResourceBundleClass.self)
#endif
// MARK: - Image Assets
public struct ImageAssetResource: Hashable {
    public var name: String
    public var bundle: Bundle
    
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

extension ImageResource {
    public init(asset: ImageAssetResource) {
        self.init(name: asset.name, bundle: asset.bundle)
    }
}

@available(iOS 13.0, *)
extension UIImage {
    public convenience init(asset: ImageAssetResource) {
        self.init(named: asset.name, in: asset.bundle, with: nil)!
    }
}

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension Image {
    public init(asset: ImageAssetResource) {
        self.init(asset.name, bundle: asset.bundle)
    }
}
#endif

@MainActor public extension ImageAssetResource {
	/// The "OleBegemann" asset catalog image resource.
	static let oleBegemann = Self.init(name: "OleBegemann", bundle: resourceBundle)

	/// The "AdamSavage" asset catalog image resource.
	static let adamSavage = Self.init(name: "AdamSavage", bundle: resourceBundle)

	/// The "MikeAsh" asset catalog image resource.
	static let mikeAsh = Self.init(name: "MikeAsh", bundle: resourceBundle)

}

